spring.application.name=trabalho06

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${SECRET_KEY}
queue.order-events=fila-pedidos-recuperacao.fifo